### ISSUE TITLE
how much time you spend when the parameters are trained

### ISSUE THREAD

**Issue by shushuzhong** [mukundkalantri23/Sign-Language-Digits-Detection#1]
thx the code you share~

the code is still running while i have waited for 30minutes but it just show the cost and the figure
is there sth wrong with my computer or?

**Comment by mukundkalantri23** [comment]
Hi @fengfenglov3 this model took around 10 minutes to process on my system. If you have copied the exact code this should be the case with you as well. But again, processing speed does depend on your system's configuration. Try running the code on cloud platforms like Gradient or Google Colab, if your system configuration is low.
